spring.application.name=msla

server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/practica2}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:lucas}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:11335577990}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

exchange.api.url=${EXCHANGE_API_URL:https://api.apilayer.com/exchangerates_data}
exchange.api.key=NjsnOKFGocWwhMjsJyz9bHcHty8jy2Fh