spring.application.name=msla

server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/practica2}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

exchange.api.url=${EXCHANGE_API_URL:https://api.apilayer.com/exchangerates_data}
exchange.api.key=${EXCHANGE_API_KEY}

app.security.username=${BASIC_AUTH_USERNAME}
app.security.password=${BASIC_AUTH_PASSWORD}
